- hosts: all
  become: true
  tasks: 
     - name: delete old deployment
       command: kubectl delete -f /home/ec2-user/Deployment.yml
     - name: delete old service
       command: kubectl delete -f /home/ec2-user/Service.yml
     - name: create new deployment
       command: kubectl apply -f /home/ec2-user/Deployment.yml
     - name: create new service
       command: kubectl apply -f /home/ec2-user/Service.yml
     - name: create new service
       command: kubectl expose deployment harish343 --type=NodePort
     - name: create new service
       command: kubectl port-forward svc/harish343 8080:8080 --address 0.0.0.0 &