kind: Deployment
apiVersion: apps/v1
metadata:
   name: harish343
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: harish343
   template:
      metadata:
        labels:
          app: harish343
      spec:
       containers:
        - name: harish343
          image: harish343/first_pipeline
          imagePullPolicy: Always
          ports:
          - containerPort: 80