kind: Service                             
apiVersion: v1
metadata:
  name: harish343
  labels:
    app: harish343
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: harish343                    
  type: LoadBalancer   